"""Update

Revision ID: 3d98140d321e
Revises: 2cbbbc835d07
Create Date: 2019-07-08 08:57:29.894087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d98140d321e'
down_revision = '2cbbbc835d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.add_column('blogs', sa.Column('blog_subject', sa.String(), nullable=True))
    op.add_column('blogs', sa.Column('blog_title', sa.String(), nullable=True))
    op.drop_column('blogs', 'pitch_id')
    op.drop_column('blogs', 'pitch_title')
    op.drop_column('blogs', 'pitch_subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('pitch_subject', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('pitch_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'blog_title')
    op.drop_column('blogs', 'blog_subject')
    op.drop_column('blogs', 'blog_id')
    # ### end Alembic commands ###
